name: aquaflow_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  flutter_native_splash: ^2.4.5
  firebase_auth: ^5.5.1
  http: ^1.3.0
  intl: ^0.20.2
  cloud_firestore: ^5.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_native_splash:
  color: "#1E1E1E"
  android_12:
    image: assets/logo.png