// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxlF02eS6ZUDwTq4l_e6eI5ME8J1CisFA',
    appId: '1:942231946447:web:15a0445ad9f48c847a63ba',
    messagingSenderId: '942231946447',
    projectId: 'aqwaflow',
    authDomain: 'aqwaflow.firebaseapp.com',
    storageBucket: 'aqwaflow.firebasestorage.app',
    measurementId: 'G-LECPK578SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1uvYCaivzsiLGbMlf2qTJMKksZPRJYMw',
    appId: '1:942231946447:android:986d4b6f48f16c437a63ba',
    messagingSenderId: '942231946447',
    projectId: 'aqwaflow',
    storageBucket: 'aqwaflow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB-6f0eCbkbRlbzTsx76zGqR58vBvkw4U',
    appId: '1:942231946447:ios:039269d425559d527a63ba',
    messagingSenderId: '942231946447',
    projectId: 'aqwaflow',
    storageBucket: 'aqwaflow.firebasestorage.app',
    iosBundleId: 'com.example.aquaflowMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB-6f0eCbkbRlbzTsx76zGqR58vBvkw4U',
    appId: '1:942231946447:ios:039269d425559d527a63ba',
    messagingSenderId: '942231946447',
    projectId: 'aqwaflow',
    storageBucket: 'aqwaflow.firebasestorage.app',
    iosBundleId: 'com.example.aquaflowMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxlF02eS6ZUDwTq4l_e6eI5ME8J1CisFA',
    appId: '1:942231946447:web:8609e1c6da0f28677a63ba',
    messagingSenderId: '942231946447',
    projectId: 'aqwaflow',
    authDomain: 'aqwaflow.firebaseapp.com',
    storageBucket: 'aqwaflow.firebasestorage.app',
    measurementId: 'G-73HJLJB9TF',
  );
}
